---
{{ $namespaceArgo := .Values.namespaceArgo}}

{{- range $name, $value := .Values.projects}}

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $name }}
  namespace: {{ $namespaceArgo | default "argo"}}
spec:
  description: {{ $value.description }}
  sourceRepos:
    {{- range $source :=  $value.sources }}
    - {{ $source }}
    {{- end }}
  destinations:
  {{- range $destname, $destvalue := $value.destinations }}
    - namespace:   {{ $destvalue.namespace }}
      server:  {{ $destvalue.server }}
  {{- end }}

  {{- if ($value.clusterResourceWhitelist) }}
  clusterResourceWhitelist:
  {{- range $name, $value := $value.clusterResourceWhitelist }}
    - group: {{ $value.group }}
      kind: {{ $value.kind }}
  {{- end }}
  {{- end }}

  {{- if ($value.namespaceResourceBlacklist) }}
  namespaceResourceBlacklist:
  {{- range $name, $value := $value.namespaceResourceBlacklist }}
    - group: {{ $value.group }}
      kind: {{ $value.kind }}
  {{- end }}
  {{- end }}

  {{- if ($value.namespaceResourceWhitelist) }}
  namespaceResourceWhitelist:
  {{- range $name, $value := $value.namespaceResourceWhitelist }}
    - group: {{ $value.group }}
      kind: {{ $value.kind }}
  {{- end }}
  {{- end }}

  orphanedResources:
     ignore:
      {{- range $ignored :=  $value.ignored }}
      - kind: {{ $ignored }}
      {{- end }}
     warn: {{ $value.warnignored | default true }}
---
  {{- end }}
